server:
  port: 8661

spring:
  application:
    name: discovery-service

eureka:
  instance:
    hostname: fake-news-eureka-server.herokuapp.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: https://fake-news-eureka-server.herokuapp.com/eureka